### ISSUE TITLE
Account Registration Bubble Error

### ISSUE THREAD

**Issue by petersenea** [essofluffy/Node-Login#1]
![bubbleerror](https://cloud.githubusercontent.com/assets/18425652/21039239/1e750b28-bda2-11e6-97a4-b0a322237014.png)

The "Please fill out this field." bubble doesn't point to the right category that was left blank. If there are more than one left blank, only one bubble is produced.

**Comment by ddehueck** [comment]
Please open this issue in proper repository: https://github.com/LACodingClub/Main-Site/issues
